---
- name: Set up Docker and deploy container
  hosts: ec2
  become: yes  # This is necessary to gain root privileges

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install git
      package:
        name: git
        state: present


    - name: Build Docker image
      docker_image:
        source: build
        build:
          path: "/home/ec2-user/todo-app"
        name: "todo-app"
        tag: "latest"

    - name: Stop any currently running container
      docker_container:
        name: "todo-app"
        state: absent

    - name: Start new Docker container
      docker_container:
        name: "todo-app"
        image: "todo-app:latest"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        env:
          DB_DSN: "{{ DB_DSN }}"

